2023-06-22 09:35:07,983 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-22 09:35:08,210 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-22 09:35:55,314 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-22 09:35:55,521 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-22 09:58:10,704 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-22 09:58:10,920 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-22 09:58:49,902 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-22 10:03:22,098 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:19:23,958 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:20:58,065 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-23 12:20:58,288 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:22:04,953 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-23 12:22:05,220 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:22:39,148 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-23 12:22:39,454 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:22:45,830 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 284, in get
    name = elem["nate"]
KeyError: 'nate'
2023-06-23 12:33:24,690 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:34:13,640 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 284, in get
    name = elem["nate"]
KeyError: 'nate'
2023-06-23 12:34:13,745 [WARNING] django.request: Not Found: /favicon.ico
2023-06-23 12:35:51,309 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-23 12:35:51,728 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:36:09,441 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-23 12:36:09,817 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:36:42,611 [ERROR] django.request: Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py", line 27, in trigger_error
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
2023-06-23 12:38:03,135 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-23 12:38:03,551 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-23 12:38:30,484 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-23 12:38:30,864 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:14:53,709 [INFO] django.utils.autoreload: /home/seryibizkit/.local/lib/python3.10/site-packages/requests/adapters.py changed, reloading.
2023-06-24 07:14:54,065 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:29:21,395 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/forms.py changed, reloading.
2023-06-24 07:29:22,012 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:29:46,869 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/forms.py changed, reloading.
2023-06-24 07:29:47,200 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:30:20,132 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/forms.py changed, reloading.
2023-06-24 07:30:20,405 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:30:31,920 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/forms.py changed, reloading.
2023-06-24 07:30:32,191 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 07:36:14,800 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 07:36:15,269 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:00:18,748 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:06:01,575 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 10:06:01,848 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:06:44,515 [WARNING] django.request: Not Found: /favicon.ico
2023-06-24 10:10:31,869 [WARNING] django.request: Not Found: /ru/admin
2023-06-24 10:11:32,898 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/forms.py changed, reloading.
2023-06-24 10:11:33,341 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:15:22,339 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 10:15:22,678 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:19:05,656 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 10:19:05,922 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:24:11,107 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 10:24:11,381 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:50:22,714 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 10:50:23,054 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:53:35,311 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 10:53:35,593 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:55:31,492 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 10:55:31,912 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 10:56:21,206 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 10:56:21,564 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:01:05,146 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:01:05,418 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:01:26,597 [WARNING] django.request: Not Found: /sentry-debug/
2023-06-24 11:07:03,686 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 11:07:03,983 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:09:01,642 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 11:09:01,934 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:09:26,632 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 11:09:26,896 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:09:51,618 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 11:09:51,890 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:12:06,747 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-24 11:12:07,040 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:14:04,634 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:14:04,948 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:15:08,586 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:15:08,906 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:15:39,786 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:15:40,083 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:18:23,712 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:18:24,099 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:19:33,760 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:19:34,131 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:21:15,751 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-24 11:21:16,020 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:23:33,385 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2023-06-24 11:32:21,115 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:32:21,518 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:33:09,757 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:33:10,054 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:33:49,132 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/models.py changed, reloading.
2023-06-24 11:33:49,409 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:34:26,416 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:34:26,676 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:35:06,751 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:35:07,026 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:35:35,866 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:35:36,130 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:36:10,064 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:36:10,346 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:36:19,824 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/urls.py changed, reloading.
2023-06-24 11:36:20,091 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:37:25,620 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:37:25,884 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:39:21,638 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/urls.py changed, reloading.
2023-06-24 11:39:21,906 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:41:45,148 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 11:41:45,418 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:44:18,361 [ERROR] django.request: Internal Server Error: /blog/article/5/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/article_detail.html
2023-06-24 11:45:25,355 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/admin.py changed, reloading.
2023-06-24 11:45:25,804 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:46:09,921 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/admin.py changed, reloading.
2023-06-24 11:46:10,213 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 11:46:44,223 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/admin.py changed, reloading.
2023-06-24 11:46:44,484 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:01:38,876 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:01:39,378 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:02:13,336 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:02:13,599 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:05:01,419 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:05:01,737 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:06:18,936 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:06:19,209 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:08:30,330 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:08:30,623 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:09:19,917 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:09:20,195 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:11:14,029 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/urls.py changed, reloading.
2023-06-24 12:11:14,298 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:11:26,753 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/urls.py changed, reloading.
2023-06-24 12:11:27,019 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:11:46,899 [WARNING] django.request: Not Found: /blog/article/6/
2023-06-24 12:11:55,522 [ERROR] django.request: Internal Server Error: /blog/articles/6/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'blogapp/articles' not found. 'blogapp/articles' is not a valid view function or pattern name.
2023-06-24 12:12:24,790 [WARNING] django.request: Not Found: /blog/articles/latets/feed
2023-06-24 12:30:54,252 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/models.py changed, reloading.
2023-06-24 12:30:54,809 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:32:18,115 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/models.py changed, reloading.
2023-06-24 12:32:18,386 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:32:52,384 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/views.py changed, reloading.
2023-06-24 12:32:52,693 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:35:25,267 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-24 12:35:25,659 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:36:10,808 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-24 12:36:11,093 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:37:35,146 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/urls.py changed, reloading.
2023-06-24 12:37:35,432 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:38:01,584 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 185, in _urls
    paginator_page = self.paginator.page(page)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 126, in paginator
    return paginator.Paginator(self._items(), self.limit)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 114, in _items
    return self.items()
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/sitemap.py", line 11, in items
    return Article.objects.filter(pud_date__isnull=False)\
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1379, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1189, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'pud_date' into field. Choices are: author, author_id, category, category_id, content, id, pub_date, tags, title
2023-06-24 12:39:52,873 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/blogapp/sitemap.py changed, reloading.
2023-06-24 12:39:53,147 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-24 12:39:57,395 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 71, in resolve_template
    return get_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sitemap.xml
2023-06-24 12:41:37,671 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-24 12:41:37,985 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 11:14:00,051 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 11:14:22,437 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/sitemaps/__init__.py", line 185, in _urls
    paginator_page = self.paginator.page(page)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/paginator.py", line 99, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 536, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 522, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 256, in get_select
    select_mask = self.query.get_select_mask()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 768, in get_select_mask
    return self._get_defer_select_mask(opts, mask)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 724, in _get_defer_select_mask
    field = opts.get_field(field_name).field
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Product has no field named 'author'
2023-06-25 11:14:22,677 [WARNING] django.request: Not Found: /favicon.ico
2023-06-25 11:59:51,087 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/sitemap.py changed, reloading.
2023-06-25 11:59:51,434 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:01:53,107 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 12:01:53,402 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:04:46,555 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 12:04:46,836 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:06:32,251 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-25 12:06:32,520 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:06:51,580 [WARNING] django.request: Not Found: /products/latest/feed
2023-06-25 12:08:05,632 [ERROR] django.request: Internal Server Error: /ru/shop/products/latest/feed/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 187, in get_feed
    title = self._get_dynamic_attr("item_title", item)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 103, in _get_dynamic_attr
    return attr(obj)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 188, in item_title
    return item.title
AttributeError: 'Product' object has no attribute 'title'
2023-06-25 12:08:26,138 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 12:08:26,563 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:14:22,544 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py changed, reloading.
2023-06-25 12:14:22,852 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:17:00,378 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-25 12:17:00,643 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:36:40,374 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:51:04,244 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-25 12:51:04,620 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:53:04,467 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-25 12:53:04,799 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 12:53:32,672 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-25 12:53:32,938 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 13:04:08,658 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py changed, reloading.
2023-06-25 13:04:08,968 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 13:05:16,975 [ERROR] django.request: Internal Server Error: /admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py", line 142, in import_csv
    safe_csv_orders(
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py", line 29, in safe_csv_orders
    orders = [
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py", line 30, in <listcomp>
    Order(**row)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "'1'": "Order.user" must be a "User" instance.
2023-06-25 13:07:21,068 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py changed, reloading.
2023-06-25 13:07:21,385 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 13:16:18,127 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py changed, reloading.
2023-06-25 13:16:18,591 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 13:23:01,521 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py changed, reloading.
2023-06-25 13:23:01,801 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 13:23:21,266 [ERROR] django.request: Internal Server Error: /admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ','

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/admin.py", line 142, in import_csv
    safe_csv_orders(
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py", line 39, in safe_csv_orders
    products: Sequence[Product] = Product.objects.only("id").filter(id__in=list(row.get("products")))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1271, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/lookups.py", line 426, in get_prep_lookup
    return super().get_prep_lookup()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/lookups.py", line 276, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2057, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got ','.
2023-06-25 13:24:22,798 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/common.py changed, reloading.
2023-06-25 13:24:23,123 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:49:41,847 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:50:02,304 [WARNING] django.request: Not Found: /favicon.ico
2023-06-25 19:50:08,305 [INFO] shopapp.views: Rendering shop index.
2023-06-25 19:53:47,100 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-25 19:53:47,517 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:55:16,566 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-25 19:55:16,923 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:56:56,167 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-25 19:56:56,448 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:57:01,835 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-25 19:57:02,095 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:57:42,151 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-25 19:57:42,439 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 19:59:22,657 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-25 19:59:22,940 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:00:15,172 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-25 20:00:15,435 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:00:40,761 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:04:11,173 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:04:11,613 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:05:15,127 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:05:15,410 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:05:56,567 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:05:56,875 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:06:39,889 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:06:40,159 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:10:19,127 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:10:19,420 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:10:46,260 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-25 20:10:46,536 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:13:02,074 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:23,280 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-25 20:13:23,665 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 20:13:27,320 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:28,234 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:28,941 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,122 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,289 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,456 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,616 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,783 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:29,936 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,096 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,263 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,430 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,590 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,772 [INFO] shopapp.views: Rendering shop index.
2023-06-25 20:13:30,951 [INFO] shopapp.views: Rendering shop index.
2023-06-26 12:29:22,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:29:30,040 [WARNING] django.request: Not Found: /favicon.ico
2023-06-26 12:29:42,988 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
TypeError: View.as_view() takes 1 positional argument but 2 were given
2023-06-26 12:32:45,688 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:32:46,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:46:15,311 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:46:15,603 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:47:40,761 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:47:41,040 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:47:50,651 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
TypeError: View.as_view() takes 1 positional argument but 2 were given
2023-06-26 12:49:48,174 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-26 12:49:48,460 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:50:34,871 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/myauth/views.py changed, reloading.
2023-06-26 12:50:35,246 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:53:43,496 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:53:43,946 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:54:57,752 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:54:58,037 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:55:06,428 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:55:06,692 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:55:39,786 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
TypeError: View.as_view() takes 1 positional argument but 2 were given
2023-06-26 12:57:00,504 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-26 12:57:00,790 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:57:06,583 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 413, in __init__
    super().__init__(kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
2023-06-26 12:57:39,832 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:57:40,176 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 12:57:46,578 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 413, in __init__
    super().__init__(kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
2023-06-26 12:59:40,067 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 12:59:40,359 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:00:15,063 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 419, in get
    self.object = self.get_object()
AttributeError: 'UserOrdersListView' object has no attribute 'get_object'
2023-06-26 13:01:19,084 [ERROR] django.request: Internal Server Error: /ru/shop/users/20/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 419, in get
    self.object = self.get_object()
AttributeError: 'UserOrdersListView' object has no attribute 'get_object'
2023-06-26 13:06:51,608 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:06:51,917 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:09:23,516 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:09:23,815 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:14:45,113 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:14:45,466 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:15:24,380 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:15:24,649 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:15:30,372 [ERROR] django.request: Internal Server Error: /ru/shop/users/20/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 417, in get
    self.object = self.get_object()
AttributeError: 'UserOrdersListView' object has no attribute 'get_object'
2023-06-26 13:18:52,080 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:18:52,366 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:18:57,662 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:18:57,918 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:19:04,833 [ERROR] django.request: Internal Server Error: /ru/shop/users/20/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 421, in get
    self.object = self.get_object()
TypeError: UserOrdersListView.get_object() missing 1 required positional argument: 'user_id'
2023-06-26 13:19:56,381 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:19:56,751 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:20:04,093 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:20:04,381 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:20:08,017 [WARNING] django.request: Not Found: /ru/shop/users/20/orders
2023-06-26 13:20:25,800 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 423, in get
    context = self.get_context_data(object=self.object)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 124, in get_context_data
    queryset = object_list if object_list is not None else self.object_list
AttributeError: 'UserOrdersListView' object has no attribute 'object_list'
2023-06-26 13:22:50,214 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:22:50,510 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:22:56,877 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 424, in get
    context = self.get_context_data(object=self.object)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 124, in get_context_data
    queryset = object_list if object_list is not None else self.object_list
AttributeError: 'UserOrdersListView' object has no attribute 'object_list'
2023-06-26 13:22:57,919 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 424, in get
    context = self.get_context_data(object=self.object)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 124, in get_context_data
    queryset = object_list if object_list is not None else self.object_list
AttributeError: 'UserOrdersListView' object has no attribute 'object_list'
2023-06-26 13:22:59,006 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 424, in get
    context = self.get_context_data(object=self.object)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 124, in get_context_data
    queryset = object_list if object_list is not None else self.object_list
AttributeError: 'UserOrdersListView' object has no attribute 'object_list'
2023-06-26 13:24:01,424 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:24:01,757 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:25:34,022 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:25:34,336 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:26:00,058 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:26:00,323 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:26:28,078 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:26:28,344 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 13:26:32,605 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 13:26:32,904 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:06:11,050 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:06:11,366 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:17:15,594 [ERROR] django.request: Internal Server Error: /ru/shop/users/2/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[1].username' from 'user[1].username'
2023-06-26 14:18:35,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:18:39,438 [ERROR] django.request: Internal Server Error: /ru/shop/users/2/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 45: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2023-06-26 14:21:11,988 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:21:12,285 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:21:22,690 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:21:22,962 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:21:46,373 [ERROR] django.request: Internal Server Error: /ru/shop/users/10/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 425, in get_context_data
    context["userinfo"] = self.owner.username
AttributeError: 'int' object has no attribute 'username'
2023-06-26 14:24:24,716 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:24:25,015 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:26:17,639 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:26:18,007 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:26:24,068 [ERROR] django.request: Internal Server Error: /ru/shop/users/10/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 427, in get_context_data
    print(context["userinfo"].username)
AttributeError: 'int' object has no attribute 'username'
2023-06-26 14:27:29,966 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:27:30,290 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:36:49,837 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:36:50,121 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:36:56,416 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:37:48,234 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:37:49,200 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:37:49,623 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:39:14,006 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 49: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:39:15,092 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 49: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:39:15,884 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 49: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2023-06-26 14:51:39,722 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:51:40,084 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:52:22,330 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_details pk=userprofile.pk' not found. 'account_details pk=userprofile.pk' is not a valid view function or pattern name.
2023-06-26 14:53:57,350 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-26 14:53:57,641 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-26 14:54:08,881 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_details pk=userprofile.pk' not found. 'account_details pk=userprofile.pk' is not a valid view function or pattern name.
2023-06-26 14:57:26,352 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_details pk=userinfo.pk' not found. 'account_details pk=userinfo.pk' is not a valid view function or pattern name.
2023-06-26 14:58:15,870 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'userprofile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'userprofile' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
2023-06-27 10:08:12,847 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:08:13,230 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:11:29,707 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:11:30,059 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:13:06,477 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:13:06,750 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:14:38,133 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-27 10:14:38,413 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:15:12,086 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 10:15:19,709 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:15:52,232 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-27 10:15:52,510 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:16:32,631 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:17:29,693 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:17:35,175 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:18:34,270 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:18:34,599 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:18:37,579 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:21:53,130 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:21:53,425 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:22:05,938 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:22:06,201 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:22:14,412 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:15,786 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:15,942 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:16,110 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:16,270 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:16,509 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:22:16,710 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:27:10,396 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:27:10,702 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:27:21,135 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:33:05,186 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:33:05,457 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:33:11,759 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:33:50,605 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-27 10:33:50,958 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:33:55,907 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/export/
2023-06-27 10:34:22,840 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/urls.py changed, reloading.
2023-06-27 10:34:23,183 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:34:30,913 [ERROR] django.request: Internal Server Error: /ru/shop/users/22/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 413, in get
    user_id = self.object.pk
AttributeError: 'UserOrdersExportView' object has no attribute 'object'
2023-06-27 10:35:43,233 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:35:43,526 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:35:52,073 [ERROR] django.request: Internal Server Error: /ru/shop/users/22/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 414, in get
    user = User.objects.get(pk=user_id)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-06-27 10:36:16,722 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:36:17,073 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:36:58,283 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:36:58,546 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:37:04,760 [ERROR] django.request: Internal Server Error: /ru/shop/users/22/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 414, in get
    user = User.objects.get(pk=user_id)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-06-27 10:38:03,219 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:38:03,660 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:38:19,200 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:38:19,471 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:38:34,729 [ERROR] django.request: Internal Server Error: /ru/shop/users/22/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 418, in get
    user = User.objects.get(pk=user_id)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-06-27 10:39:28,079 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:39:28,438 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:39:35,799 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:39:36,062 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:39:40,369 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 10:41:07,328 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-27 10:41:07,603 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:41:14,538 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 10:44:09,741 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:44:10,018 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:44:16,164 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 415, in get
    serializer = self.get_serializer(products, many=True)
AttributeError: 'UserOrdersExportView' object has no attribute 'get_serializer'
2023-06-27 10:44:16,480 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 415, in get
    serializer = self.get_serializer(products, many=True)
AttributeError: 'UserOrdersExportView' object has no attribute 'get_serializer'
2023-06-27 10:44:38,800 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:44:39,134 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:44:43,869 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 415, in get
    serializer = self.get_serializer(orders, many=True)
AttributeError: 'UserOrdersExportView' object has no attribute 'get_serializer'
2023-06-27 10:46:04,272 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-27 10:46:04,549 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:46:48,767 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:46:49,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:51:05,654 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:51:05,940 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:51:15,044 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'delivery_address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 417, in get
    orders_data = OrderSerializer(orders).data
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `delivery_address` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'delivery_address'.
2023-06-27 10:51:49,680 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'delivery_address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 417, in get
    orders_data = OrderSerializer(orders).data
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `delivery_address` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'delivery_address'.
2023-06-27 10:52:39,133 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:52:39,432 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:52:47,778 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py", line 422, in get
    return JsonResponse({"orders": orders_data})
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/http/response.py", line 748, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/seryibizkit/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type OrderSerializer is not JSON serializable
2023-06-27 10:53:19,580 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:53:19,938 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:55:08,598 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:55:08,911 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:56:39,041 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:56:39,392 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:57:01,059 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:57:01,315 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:57:26,819 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 10:57:27,943 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 10:59:14,278 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 10:59:14,549 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 10:59:21,558 [WARNING] django.request: Not Found: /ru/shop/users/22/orders/export/
2023-06-27 11:31:34,644 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:31:34,957 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:32:35,322 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:32:35,596 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:34:55,721 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:34:56,006 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:35:44,321 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:35:44,621 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:37:49,672 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:37:50,019 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:38:15,824 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:38:16,097 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:43:07,806 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/mysite/settings.py changed, reloading.
2023-06-27 11:43:08,125 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-27 11:45:57,933 [INFO] django.utils.autoreload: /home/seryibizkit/Документы/PhycharmProject/dpo_python_django/mysite/shopapp/views.py changed, reloading.
2023-06-27 11:45:58,215 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-29 07:02:34,600 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-29 07:03:02,740 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
